workflows:
  ios-release:
    name: iOS Release Build
    environment:
      xcode: latest
      flutter: stable
      ruby: 3.2.2
      cocoapods: 1.16.2
      vars:
        BUNDLE_ID: "NetGague.Games"
      groups:
        - app_store_credentials
    scripts:
      - name: Set Ruby version manually
        script: |
          rbenv install -s 3.2.2
          rbenv global 3.2.2
          ruby -v
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: "$APP_STORE_CONNECT_PRIVATE_KEY"
        key_id: "$APP_STORE_CONNECT_KEY_IDENTIFIER"
        issuer_id: "$APP_STORE_CONNECT_ISSUER_ID"
        submit_to_testflight: true
