workflows:
  ios-release:
    name: iOS Release Build
    environment:
      xcode: latest
      flutter: stable
      ruby: 3.3.6
      cocoapods: 1.16.2
      ios_signing:
        certificates:
          - Cole iOS Distribution Cert
        provisioning_profiles:
          - Cole iOS Provisioning Profile
      vars:
        BUNDLE_ID: "NetGague.Games"
      groups:
        - app_store_credentials
    scripts:
    
      - name: Set Ruby version manually
        script: |
          rbenv install -s 3.3.6
          rbenv global 3.3.6
          ruby -v
      
      - name: Clean build state
        script: flutter clean

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Warm Up iOS Toolchain
        script: flutter build ios --release

      - name: Set up Code Signing
        script: xcode-project use-profiles

      - name: Build iOS IPA
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: "$APP_STORE_CONNECT_PRIVATE_KEY"
        key_id: "$APP_STORE_CONNECT_KEY_IDENTIFIER"
        issuer_id: "$APP_STORE_CONNECT_ISSUER_ID"
        submit_to_testflight: true
